apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: project1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhcnNoYWRwcm9qZWN0MS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkRwQVFYSnphR0ZrTVRJeiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
