apiVersion: v1
kind: Service
metadata:
  name:  project1-service
  namespace: project1
spec:
  type: NodePort
  selector:
    app: valaxy-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
